name: BetterTeams
version: 3.0.10
author: booksaw
description: A plugin to create teams with other players
main: com.booksaw.betterTeams.Main
api-version: 1.15
softdepend:
- PlaceholderAPI
- HolographicDisplays
- Vault
website: https://github.com/booksaw/BetterTeams
commands:
   team:
      description: All commands for teams
      usage: /<command> help
      permission: betterTeams.standard
   teamadmin:
      description: All admin commands for teams
      usage: /<command> help
      permission: betterTeams.admin
      aliases:
      - teama
permissions:
   betterTeams.standard:
      description: This permission gives the user access to the teams system (joining, leaving teams etc.)
      default: true
   betterTeams.admin:
      description: This permission gives the user access to the admin system for BetterTeams
      default: op
   betterTeams.join:
      default: true
      description: Allows access to /team join
   betterTeams.ban:
      default: true
      description: Allows access to /team ban
   betterTeams.chat:
      default: true
      description: Allows access to /team chat
   betterTeams.create:
      default: true
      description: Allows access to /team create
   betterTeams.promote:
      default: true
      description: Allows access to /team promote
   betterTeams.description:
      default: true
      description: Allows access to /team description
   betterTeams.disband:
      default: true
      description: Allows access to /team disband
   betterTeams.home:
      default: true
      description: Allows access to /team home
   betterTeams.invite:
      default: true
      description: Allows access to /team invite
   betterTeams.kick:
      default: true
      description: Allows access to /team kick
   betterTeams.info:
      default: true
      description: Allows access to /team info
   betterTeams.leave:
      default: true
      description: Allows access to /team leave
   betterTeams.name:
      default: true
      description: Allows access to /team name
   betterTeams.open:
      default: true
      description: Allows access to /team open
   betterTeams.teamName:
      default: true
      description: Users with this permission will have their team name dispalyed above their head
   betterTeams.balance:
      default: true
      description: Allows access to /team bal, /team withdraw and /team balance
   betterTeams.admin.chatspy:
      default: op
      description: Allows access to /teama chatspy
   betterTeams.title:
      default: true
      description: Allows access to /team title
   betterTeams.title.color.color:
      default: op
      description: Allows the user to add color codes into their titles
   betterTeams.title.color.format:
      default: op
      description: Allows the user to add format codes into their titles
   betterTeams.title.self:
      default: op
      description: Allows the user to change their own title even if they are not the team owner
   betterTeams.unan:
      default: true
      description: Allows access to /team unban
   betterTeams.sethome:
      default: true
      description: Allows access to /team sethome
   betterTeams.demote:
      default: true
      description: Allows access to /team demote
   betterTeams.top:
      default: true
      description: Allows access to /team top
   betterTeams.rank:
      default: true
      description: Allows access to /team rank
   betterTeams.title.:
      default: true
      description: Allows access to /team title
   betterTeams.title.color.color:
      default: op
      description: Allows access to color codes wtih /team title
   betterTeams.title.color.format:
      default: op
      description: Allows access to formatting codes with /team title
   betterTeams.title.self:
      default: op
      description: Allows access to change their own title, even when they are not team owner
   betterTeams.admin.version:
      default: op
      description: Allows access to /teama version
   betterTeams.admin.home:
      default: op
      description: Allows access to /teama home
   betterTeams.cooldown.bypass:
      default: op
      description: Allows access to bypass command cooldown
   betterTeams.cost.bypass:
      default: op
      description: Allows access to bypass command cost
   betterTeams.admin.chatspy:
      default: op
      description: Allows access to /teama chatspy
   betterTeams.admin.title:
      default: op
      description: Allows access to /teama title