name: Release

on:
  push:
    branches:
      - master

jobs:
  main:
    name: NPM Release
    runs-on: ubuntu-latest

    steps:
      - name: Generate changelog
        uses: heinrichreimer/action-github-changelog-generator@v2.2
